[build-system]
requires = ['setuptools >= 44', 'wheel', 'setuptools_scm[toml] >= 3.4.3']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 127
skip-string-normalization = true
target-version = ['py38', 'py37', 'py36', 'py35', 'py27']

[tool.isort]
profile = "black"
lines_between_types = 1
lines_after_imports = 2
line_length = 127
known_first_party = "build"
skip = []  # "build" is included in the default skip list

[tool.setuptools_scm]
